export const words:string[] = [
    "Airport",
    "Home",
    "Jupiter",
    "Earth",
    "Shopping Mall",
    "Rocketship",
    "Kitchen",
    "Eiffel Tower",
    "Cell Tower",
    "Balcony",
    "School",
    "Zoo",
    "Cafe",
    "Space Station",
    "Backpack",
    "Kindergarten",
    "Google",
    "Home",
    "Internet",
    "Gas Station",
    "USA",
    "Apple(Fruit)",
    "Video Player",
    "T-Shirt",
    "Wallet",
    "Bridge",
    "Theater",
    "Sports Center",
    "Gym",
    "Clothing Store",
    "Bakery",
    "Library",
    "Police Station",
    "A Park",
    "Subway",
    "Church",
    "Bus Stop",
    "Museum",
    "Credit/Debit Card",
    "Toilet",
    "What? Where? When?",
    "Mountains",
]

export default words;